apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: dockerweb
  namespace: microservices
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: dokerweb
        tier: backend
        track: stable
        version : v2
        
    spec:
      containers:
        - name: docerweb
          image: "ultradev/dockerwebv2.0"
          lifecycle:
