kind: Service
apiVersion: v1
metadata:
  name: cktfrmt
  namespace: microservices
spec:
  selector:
    app: cktfrmt
    tier: backend
    
  ports:
    - protocol: "TCP"
      port: 8181
      targetPort: 8080
  type: NodePort
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: cktfrmt
  namespace: microservices
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: cktfrmt
        tier: backend
        track: stable
    spec:
      containers:
        - name: docerweb
          image: "ultradev/dockerweb:latest"
          lifecycle:
